### ISSUE TITLE
[Bug]: Netlify deploy failing due to missing netlify-handler.js

### ISSUE THREAD

**Issue by azinod** [web-infra-dev/modern.js#8379]
### Version

```sh
System:
    OS: macOS 15.7.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 301.03 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 145.0.7632.110
    Edge: 145.0.3800.70
    Firefox: 147.0.4
    Safari: 26.3
  npmPackages:
    @modern-js/app-tools: 3.0.2 => 3.0.2 
    @modern-js/runtime: 3.0.2 => 3.0.2 
    @modern-js/server-runtime: 3.0.2 => 3.0.2 
    @modern-js/tsconfig: 3.0.2 => 3.0.2
```

### Details

We started getting issues to deply to Netlify after upgrading to v3.0.2

When I run `MODERNJS_DEPLOY=netlify npx modern deploy`, the generated output files in `.netlify/functions` include a `netlify-handler.cjs`, however when I deploy to netlify the function initalization fails because it is looking for `netlify-handler.js` (regular JS file, not CJS)

I am guessing the issue might have to do with the line below that tries to import `netlify-handler.js` instead of `netlify-handler.cjs`
https://github.com/web-infra-dev/modern.js/blob/5269eac08597526590b729f8c5a29bd6ff05f534/packages/solutions/app-tools/src/plugins/deploy/platforms/netlify.ts#L141-L143

This is the error I get:
```
Feb 25, 02:55:57 PM: ERROR  Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module './netlify-handler.js'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module './netlify-handler.js'","Require stack:","- /var/task/index.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1192:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1235:21)","    at async start (file:///var/runtime/index.mjs:1454:23)","    at async file:///var/runtime/index.mjs:1464:1"]}
```

Can you please check?

### Reproduce link

Don't have one yet

### Reproduce Steps

To test this, you need to setup a new project and a netlify app and test deploy to netlify using this build command: `MODERNJS_DEPLOY=netlify npx modern deploy`

**Comment by azinod** [comment]
I created script to replace `netlify-handler.js` by `netlify-handler.cjs` to test and got a different error:

```
Feb 25, 03:32:55 PM: ERROR  Uncaught Exception 	{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1238:15)","    at async start (file:///var/runtime/index.mjs:1454:23)","    at async file:///var/runtime/index.mjs:1464:1"]}
```

Reverting ModernJS to v2 fixes the issue, but we really wanted v3 since we are leveraging module-federation and SSR

**Comment by zllkjc** [comment]
Thanks for feedback, let's check it~

**Comment by azinod** [comment]
Hello @clChenLiang and @zllkjc,

I cloned this repository locally to test the changes from this [PR](https://github.com/web-infra-dev/modern.js/pull/8428) and while the changes fix the initial issue, I faced a few other issues to get things actually running.

I put together [this followup PR](https://github.com/web-infra-dev/modern.js/pull/8439) with the other changes that I had to do to have my ModernJS app properly deploy and run on Netlify as a Function.

The changes in the PR are probably not the best solutions to the issues I faced, but they at least serve to illustrate other potential issues that might need to be addressed and hint at what could be the proper solution to get them fixed.

Can you please take a look and see if they make sense?

**Comment by clChenLiang** [comment]
@azinod Hi, here we saw your pr, it seems fine. 

The more available fixture will after my test, maybe to use a middleware to transfer the two request. It needs some time for us. Can you use your fork version to instead ModernJs if your problem can be fixed by. 

As we see, the hono has set the request for a long time, and the old version ModernJs has not meet the compatibility problem. we will to find why this version

**Comment by azinod** [comment]
@clChenLiang thank you for checking this.

We already reverted to ModernJS v2.7.8 for the time being until we can get the definitive fix in the main ModernJS repository.

Can we keep this issue open for the time being so we can follow status updates?

Thank you!

**Comment by zllkjc** [comment]
@azinod Sure, keep this issue, we will check it asap~

**Comment by clChenLiang** [comment]
@azinod hi, after we carefully check. We found that make this error is the netlify function devide different runtime api version with the handler.cjs's export way.

<img width="1428" height="814" alt="Image" src="https://github.com/user-attachments/assets/b1b325df-5c55-448f-96ca-fe7e57f9bdae" />

and this make the hone received a plant object instead the Request:

<img width="1552" height="2046" alt="Image" src="https://github.com/user-attachments/assets/946fd29f-aa7a-4120-9706-71238da17e65" />

The normal Request should be:

<img width="974" height="1234" alt="Image" src="https://github.com/user-attachments/assets/15cabc5a-c533-4189-b2a7-7e4721fc9ae0" />

**Comment by clChenLiang** [comment]
We fixed in https://github.com/web-infra-dev/modern.js/pull/8477.
If you check this commit not has other problem, we will publish in 2026-03-25

**Comment by azinod** [comment]
Thank you @clChenLiang for working on this, I will give it a shot this week.

**Comment by clChenLiang** [comment]
[0.0.0-nightly-20260323162459](https://www.npmjs.com/package/@modern-js/app-tools/v/0.0.0-nightly-20260323162459)
a nightly version

**Comment by kritb-earnin** [comment]
@clChenLiang Thanks for the update! I tested the fix using the nightly version, but I encountered the following error in my Netlify function logs:
```
ERROR  Error creating server: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'server' imported from /var/task/node_modules/@modern-js/utils/dist/cjs/cli/require.js
Did you mean to import "file:///var/task/server/modern.server.js"?
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:314:9)
    at packageResolve (node:internal/modules/esm/resolve:773:81)
    at moduleResolve (node:internal/modules/esm/resolve:859:18)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:989:14)
    at defaultResolve (node:internal/modules/esm/resolve:1032:79)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:731:20)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:310:38)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:664:36)
    at TracingChannel.tracePromise (node:diagnostics_channel:350:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
Do you have any suggestions on how to resolve this?

## Version
```
"@modern-js/app-tools": "0.0.0-nightly-20260323162459"
"@modern-js/runtime": "0.0.0-nightly-20260323162459" 
"@modern-js/server-runtime": "0.0.0-nightly-20260323162459"
"@modern-js/tsconfig": "0.0.0-nightly-20260323162459"
```

**Comment by clChenLiang** [comment]
@kritb-earnin could you gave an re produce env, or mvp code ?
Seem like your server.js file failed, if import not from your customer code, it might be another bug

**Comment by kritb-earnin** [comment]
I will try summarize from what I've found:

**Problem:** Netlify deployments that use `createNetlifyFunction` + a custom `server/modern.server` entry can fail at runtime with Node ESM errors such as **`Cannot find package 'server'`** (and a hint to use `file:///…/server/modern.server.js`). The failure originates in **`@modern-js/utils`** (`dist/cjs/cli/require.js`), called from **`loadServerRuntimeConfig`** (`@modern-js/server-core`).

**Root cause (two related bugs):**

1. **Generated Netlify handler** (e.g. `.netlify/functions/index.js`) sets `serverConfigPath` to a **bare relative** string like `"server/modern.server"` (no `__dirname`, no `file://`).

2. **`requireExistModule`** then:
   - Uses **`fs.existsSync`** on paths built from that string, which are resolved relative to **`process.cwd()`**, not necessarily relative to the function bundle’s **`pwd` / `__dirname`** (even though `prodServerOptions.pwd` is set to `__dirname`).
   - Passes the matched path (e.g. `server/modern.server.js`) into **`compatibleRequire`**, which does **`require(path)`** from **inside** `@modern-js/utils`. A string like `server/modern.server.js` is not resolved as “file next to the Lambda bundle”; it follows normal Node resolution (often wrong here).
   - On **`ERR_REQUIRE_ESM`**, **`importPath`** forwards **non-absolute** paths to **`import()`** unchanged. In Node, **`import('server/modern.server.js')`** is treated as a **package** named `server`, not `/var/task/server/modern.server.js`, which matches the observed error and Node’s suggested `file://` URL.

**Expected behavior:** Loading `modern.server` for the Netlify function should resolve **from the function bundle directory** (`pwd` / `__dirname` of the emitted handler), and any dynamic `import()` should use a **file URL** or a specifier that Node’s ESM loader accepts for that file (e.g. absolute path → `pathToFileURL`).

**Suggested fix (any one or combination):**

- **Emit** `serverConfigPath` in the Netlify template as something like  
  `require('node:path').join(__dirname, 'server', 'modern.server')`  
  (extensionless base so `requireExistModule` can still try `.ts` / `.js`), **or** emit an absolute/file-URL-safe path tied to `__dirname`.
- **Or** change **`requireExistModule` / `loadServerRuntimeConfig`** to resolve the config path with **`path.join(pwd, …)`** (using the same `pwd` passed into `createNetlifyFunction`) instead of relying on `cwd`-relative `existsSync`.
- **Or** fix **`importPath`** so that for dynamic `import()`, **relative** paths are resolved to an absolute path and then **`pathToFileURL`**, not passed through as bare specifiers.

**Repro context:** `@modern-js/prod-server` Netlify output + `@modern-js/utils@3.1.x` + Node 20+ on Netlify (`/var/task`).

**Comment by kritb-earnin** [comment]
@clChenLiang I tried step by step to replicate the issue and I finally found out that whenever we add cache setup from `@modern-js/runtime/cache` as below:

```ts
import { CacheSize, configureCache } from '@modern-js/runtime/cache';

export function initializeCache(): void {
  configureCache({ maxSize: CacheSize.MB * 250 });
}
```

to `modern.server.ts`, it breaks the Netlify function as mentioned https://github.com/web-infra-dev/modern.js/issues/8379#issuecomment-4127525550

**Comment by clChenLiang** [comment]
@kritb-earnin 
Your summarize were totally right. And we fixed in [fix-mr](https://github.com/web-infra-dev/modern.js/pull/8543)

And we test the fixture by a netlify usages with customer server to change the body:

<img width="1768" height="1232" alt="Image" src="https://github.com/user-attachments/assets/265e3852-ae7e-4c6a-963c-8ebbe32d8e49" />

and in the [app link ](https://69dca8f4926542198eade04f--modern-js-netlyfi-02.netlify.app), got the 

<img width="3248" height="1394" alt="Image" src="https://github.com/user-attachments/assets/494aec0b-6c56-4bc6-bb39-5aa6469c97c8" />

May you try the check this by `@modern-js/app-tools:0.0.0-canary-20260413083704`

**Comment by zllkjc** [comment]
released in 3.1.4, I will close this issue.

If have other problem, feel free to comment here~

**Comment by kritb-earnin** [comment]
@zllkjc @clChenLiang thank you for your support 👍🏻
